import { useEffect, useState } from 'react'
import Navbar from '../components/Navbar'
import Hero from '../components/Hero'
import SectionTitle from '../components/SectionTitle'
import FoodCard from '../components/FoodCard'
import Reservation from '../components/Reservation'
import Footer from '../components/Footer'
import grill from '../assets/images/grill.jpg'; import cocktail from '../assets/images/cocktail.jpg'; import interior from '../assets/images/interior.jpg'; import wings from '../assets/images/wings.jpg'; import burger from '../assets/images/burger.jpg'; import coffee from '../assets/images/coffee.jpg'; import testimonial from '../assets/images/testimonial.jpg'; import chef1 from '../assets/images/chef-1.jpg'; import chef2 from '../assets/images/chef-2.jpg'; import chef3 from '../assets/images/chef-3.jpg'

const dishes=[{name:'Crispy Fried Chicken',desc:'Spiced, crisp and golden',price:'10.85',image:wings,cat:'Steak'},{name:'Shroom Bacon Burger',desc:'Smoky, juicy and stacked',price:'11.75',image:burger,cat:'Burger'},{name:'Delicious Black Coffee',desc:'Deep roasted house blend',price:'7.75',image:coffee,cat:'Coffee'}]
const menu={Dessert:['Chocolate fondant','Lemon tart','Berry panna cotta'],Steak:['BBQ beef rib','Grilled sirloin','Chicken wings'],Coffee:['Flat white','Iced latte','House espresso'],Burger:['Shroom bacon burger','Classic smash','Crispy chicken bun']}

export default function Home(){
 const [category,setCategory]=useState('Steak')
 useEffect(()=>{const els=document.querySelectorAll('.reveal'); const obs=new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.12}); els.forEach(el=>obs.observe(el)); return()=>obs.disconnect()},[])
 return <><Navbar/><main><Hero/>
 <section id="about" className="about container reveal"><div><SectionTitle eyebrow="ABOUT THE FOOD RESTAURANT" title="New Ground with Dishes to be Enjoyed"/><div className="experience"><b>15</b><span>Years of<br/>good food</span></div></div><div className="about-copy"><p>Real cooking has no shortcuts. We bring honest ingredients, confident seasoning and a generous spirit to every table.</p><div className="founder"><span>WJ</span><div><strong>Williams James</strong><small>Director and Chief Operations Officer</small></div></div></div><div className="about-cards">{[[grill,'Restaurant'],[cocktail,'Cocktail Bar'],[interior,'Private Dining']].map(([img,title])=><article key={title}><img src={img} alt={title}/><strong>{title}</strong></article>)}</div></section>
 <section id="menu" className="menu-section container reveal"><div className="category-tabs">{Object.keys(menu).map((cat,i)=><button className={category===cat?'active':''} onClick={()=>setCategory(cat)} key={cat}><span>{['◉','♨','☕','▰'][i]}</span>{cat}</button>)}</div><div className="menu-board"><div className="plate-wrap"><img src={category==='Coffee'?coffee:category==='Burger'?burger:wings} alt={`${category} selection`}/></div><div><p className="menu-label">OUR {category.toUpperCase()} SELECTION</p>{menu[category].map((item,i)=><div className="menu-row" key={item}><span><b>{item}</b><small>Freshly prepared with our signature touch</small></span><strong>${[18,16,14][i]}.00</strong></div>)}</div></div><SectionTitle eyebrow="GOOD FOOD, GOOD MOOD" title="Discover Menu" center/><div className="promos"><article style={{backgroundImage:`linear-gradient(90deg,#090909 20%,transparent),url(${grill})`}}><h3>Steaks & BBQ</h3><p>Charred favourites, served hot.</p><b>$17.00</b></article><article style={{backgroundImage:`linear-gradient(90deg,#090909 20%,transparent),url(${cocktail})`}}><h3>Cocktails</h3><p>Handcrafted classics to toast.</p><b>$12.00</b></article></div></section>
 <Reservation/>
 <section className="featured reveal"><div className="container"><SectionTitle eyebrow="CHEF'S SELECTION" title="Featured Dishes" center/><div className="food-grid">{dishes.map(item=><FoodCard key={item.name} item={item}/>)}</div><div className="carousel-dots"><i/><i/><i/></div></div></section>
 <section id="reviews" className="reviews container reveal"><div><SectionTitle eyebrow="TESTIMONIALS & REVIEWS" title="Our Customer Feedbacks"/><blockquote>“A good restaurant is like a vacation; it transports you, and it becomes a lot more than just about the food. All great deeds are served at great discounts.”<strong>— Brielle Hamit</strong></blockquote></div><div className="review-collage"><img src={testimonial} alt="Restaurant moments"/><span>4.9<br/><small>★★★★★</small></span></div></section>
 <section className="experts container reveal"><SectionTitle eyebrow="PASSION ON EVERY PLATE" title="Meet Our Experts" center/><div className="chef-grid">{[[chef1,'Thomas Walim','Dessert specialist'],[chef2,'James Johnson','Chef Master'],[chef3,'Room Minal','Pastry specialist']].map(([img,name,role])=><article key={name}><img src={img} alt={name}/><span>{role}</span><h3>{name}</h3><p>Fresh · Seasonal · Memorable</p></article>)}</div></section>
 <section className="app-banner reveal"><div><span>BEST APP FOR FOOD ORDERING</span><h2>Manage Your Restaurant<br/>Anytime! Anywhere!</h2><p>Instant ordering · Secure payments · Exclusive offers</p><div><button>▶ Google Play</button><button> App Store</button></div></div><div className="phone">TasteNest<br/><b>Your favourites,<br/>one tap away.</b></div></section>
 <section className="news container reveal"><SectionTitle eyebrow="FROM OUR KITCHEN" title="Recent News" center/><div className="news-grid"><article><img src={grill} alt="Creamy chicken dish"/><div><span>April 8, 2026</span><h3>Creamy Chicken Alfredo</h3><p>By TasteNest Kitchen</p></div></article><article><img src={interior} alt="Restaurant dining room"/><div><span>April 4, 2026</span><h3>Air Fryer Salmon</h3><p>By Williams James</p></div></article></div></section>
 <section id="gallery" className="gallery container reveal"><div>{[wings,burger,coffee,cocktail,grill,interior].map((img,i)=><img key={i} src={img} alt="TasteNest food and restaurant gallery"/>)}</div><a href="#home"><b>◎</b> Follow @tastenest</a></section>
 </main><Footer/></> }
